### ISSUE TITLE
Possible bug in parameter binding

### ISSUE THREAD

**Issue by DavidFluck** [cloudera/impyla#172]
I'm attempting to use parameter binding in Impyla and I think there's a bug in the escaping [here](../blob/master/impala/interface.py#L240) and [here](../blob/master/impala/interface.py#L226). When attempting to perform a query with substitution, such as: `SELECT * FROM table_name WHERE %(thing)s > 100`, the query produced by Impyla ends up like: `SELECT * FROM table_name WHERE 'column_name' > 100`. Impala then complains that strings and ints can't be compared (understandably). I think the problem is that column names are identifiers, whereas single quoted strings are literals. I poked at the code and found the two lines linked above, which seem to be the culprits. Query parameters are indiscriminately being quoted, which you don't always want.

Am I wrong or is this a bug? If so, I'd be willing to try to submit a patch.

**Comment by mariusvniekerk** [comment]
In impala column names are quoted with backticks

**Comment by mariusvniekerk** [comment]
In impala quotes of identifiers are done with backticks

**Comment by DavidFluck** [comment]
Right, but the code in interface.py, `string_parameters[name] = "'" + _escape(value) + "'"`, puts single quotes around every parameter, which throws an analysis exception.

**Comment by laserson** [comment]
Interestingly, the PEP 249 spec states in a footnote that values provided in the `parameters` arg should be provided "as is" and not require the client to perform any kind of escaping.  In practice, this is definitely not true (and also a bit unintuitive), and the other DB API impls also perform escaping.

My impression is also that the parameters functionality is provided in cases where the user wants to provide many *literal* values to plug into a single query.  The use case you're describing is actually trying to use this mechanism to generate a series of semantically different queries, since you're iterating over different colums.

**Comment by DavidFluck** [comment]
If I understand correctly, then how would one pass user-supplied column names into a query safely?

**Comment by laserson** [comment]
I'm not a SQL expert, but I would guess that passing user-supplied column names is probably considered more dangerous than passing literals.  Maybe the best approach is to sanitize it in a separate chunk of code that generates the query string that is then passed to `execute()`?

**Comment by DavidFluck** [comment]
Oh, it looks like, at least per PEP 249, you're _not_ supposed to be able to bind identifier values in queries, only literals: http://stackoverflow.com/questions/6514274/how-do-you-escape-strings-for-sqlite-table-column-names-in-python Okay, I'll escape column names myself then. Thanks and sorry for the confusion; I should've researched more carefully!
