### ISSUE TITLE
v0.14.2.2 is a wrong tag!!!!

### ISSUE THREAD

**Issue by gentleKun** [cloudera/impyla#345]
v0.14.2.2 is a wrong tag!!!!

**Comment by kinger310** [comment]
seems that this tag is tagged to the project 2 years ago :）

**Comment by dknupp** [comment]
@gentleKun -- thanks! I'll push a new tag today.

**Comment by dknupp** [comment]
Ah, I think I see what you're talking about now. v0.14.2.2 is, in fact, the right tag, but it's confusing because it points to the same commit at 0.14.1. Sadly, this is by intention.

When 0.14.2 was released, we quickly found some build issues that were breaking users' environments. Because it wasn't clear that the issues could be fixed immediately, and because there's no way to revert a release on pypi, the quickest solution to fix those broken environments was to re-release the last working commit under a new version number. This approach is described here:

https://doughellmann.com/blog/2016/02/25/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/

So this is correct:
```
$ git rev-list -n 1 v0.14.1
6980dda32350f0b43d2069978815e515a04283e4    # last working commit
$ git rev-list -n 1 v0.14.2
1ef84dba5a37c9aa4020f05895e371605513ea62    # broken commit
$ git rev-list -n 1 v0.14.2.2
6980dda32350f0b43d2069978815e515a04283e4    # points to same commit as 0.14.1
```
