### ISSUE TITLE
Remove usage of set literals

### ISSUE THREAD

**Issue by joemcdonnell** [cloudera/impyla#375]
Python 2.6 does not support set literals. Currently, interface.py has one location that uses a set literal:
https://github.com/cloudera/impyla/blob/86ca0d5507fcdaa0891b4d425ec81a22424332f5/impala/interface.py#L229
To maintain compatibility with Python 2.6, this can be converted to use a list:
`    if paramstyle in ('named', 'pyformat'):`
There may be other locations with set literals, so it would be useful to have some way to test syntax with Python 2.6.

**Comment by timarmstrong** [comment]
I was able to run the tests in a centos 6 container with the fix.

`# On host:
git archive --prefix=impyla/ -o /tmp/impyla.tar FETCH_HEAD
docker run -v /tmp/impala.tar:/tmp/impala.tar -it centos:6  bash

# In container:
yum install -y epel-release
yum install -y python-pip pytest gcc python-devel
pip install six bitarray thrift unittest2

cd /tmp
tar xvf impyla.tar
cd impyla
export IMPYLA_TEST_HOST=<host ip>
py.test impala --verbose
`

I couldn't install sqlalchemy, so some tests failed, and other failed for other reasons, but looks the same otherwise as on an ubuntu 16. host.

`
[root@fa957af8e35f impala]# py.test impala --connect
================================================ test session starts =================================================
platform linux2 -- Python 2.6.6 -- pytest-2.4.2
collected 43 items / 1 errors 

impala/tests/test_data_types.py .
impala/tests/test_dbapi_compliance.py ...............F....F....F.........
impala/tests/test_hive.py .
impala/tests/test_query_parameters.py ......

======================================================= ERRORS =======================================================
__________________________________ ERROR collecting impala/tests/test_sqlalchemy.py __________________________________
impala/tests/test_sqlalchemy.py:17: in <module>
>   from sqlalchemy.engine import create_engine
E   ImportError: No module named sqlalchemy.engine
====================================================== FAILURES ======================================================
____________________________________________ ImpalaDBAPI20Test.test_close ____________________________________________

self = <impala.tests.test_dbapi_compliance.ImpalaDBAPI20Test testMethod=test_close>

    def test_close(self):
        con = self._connect()
        try:
            cur = con.cursor()
        finally:
            con.close()
    
        # cursor.execute should raise an Error if called after connection
        # closed
>       self.assertRaises(self.driver.Error,self.executeDDL1,cur)
E       AssertionError: Error not raised by executeDDL1

impala/tests/_dbapi20_tests.py:380: AssertionError
_________________________________________ ImpalaDBAPI20Test.test_description _________________________________________

self = <impala.tests.test_dbapi_compliance.ImpalaDBAPI20Test testMethod=test_description>

    def test_description(self):
        con = self._connect()
        try:
            cur = con.cursor()
            self.executeDDL1(cur)
            self.assertEqual(cur.description,None,
>               'cursor.description should be none after executing a '
                'statement that can return no rows (such as DDL)'
                )
E               AssertionError: [('summary', 'STRING', None, None, None, None, None)] != None : cursor.description should be none after executing a statement that can return no rows (such as DDL)

impala/tests/_dbapi20_tests.py:295: AssertionError
__________________________________________ ImpalaDBAPI20Test.test_fetchone ___________________________________________

self = <impala.tests.test_dbapi_compliance.ImpalaDBAPI20Test testMethod=test_fetchone>

    def test_fetchone(self):
        con = self._connect()
        try:
            cur = con.cursor()
    
            # cursor.fetchone should raise an Error if called before
            # executing a select-type query
            self.assertRaises(self.driver.Error,cur.fetchone)
    
            # cursor.fetchone should raise an Error if called after
            # executing a query that cannnot return rows
            self.executeDDL1(cur)
>           self.assertRaises(self.driver.Error,cur.fetchone)
E           AssertionError: Error not raised by fetchone

impala/tests/_dbapi20_tests.py:514: AssertionError
=================================== 3 failed, 40 passed, 1 error in 107.40 seconds ===================================
`
