### ISSUE TITLE
lack of support in python3 in impala/_thrift_gen/RuntimeProfile/ttypes.py 

### ISSUE THREAD

**Issue by kfiryed** [cloudera/impyla#408]
I use this when I process the profiles log files and there is a use of the keyword xrange in this file
so it can not run on python3

**Comment by timarmstrong** [comment]
We definitely don't officially support this use case since that generated code is just an implementation detail of Impyla. I can give you pointers on how you might solve the problem though.

We use thriftpy2 to support Python 3, in Impyla at least - see https://github.com/cloudera/impyla/blob/master/impala/_thrift_api.py#L70

Otherwise if you had specific requirements for generated python output you would have to run the thrift compiler on the .thrift files. The original source of them is here.

Impyla does have this copy of them - https://github.com/cloudera/impyla/tree/master/impala/thrift

**Comment by kfiryed** [comment]
So I would like to get help, I want to parse the profiles impala writes to /var/log/impalad/profiles/
I used the code here: https://github.com/apache/impala/blob/master/lib/python/impala_py_lib/profiles.py
but you say this is not supported
so how can I read those files

**Comment by timarmstrong** [comment]
@kfiryed my point was that parsing Impala runtime profiles is not an intended use case for the Impyla library - you are trying to use some classes that are internal to Impyla and not part of the interface (Impyla is just a client library). So I don't want to keep an Impyla issue open about this.

The runtime profile log is a low-level supported interface for Apache Impala. user@impala.apache.org is a good place for questions about this. We had a discussion on that list a while back about this - http://mail-archives.apache.org/mod_mbox/impala-user/201908.mbox/%3CCAEoRBexmjJ7hNfHo_yLFyc0KGQDvMPKNTH--VPOfTO-w=X18qQ@mail.gmail.com%3E

There's a basic python profile library and script in the Apache Impala repo that are probably what you're looking for: https://github.com/apache/impala/blob/master/bin/parse-thrift-profile.py

It's tied into the Impala development environment, but you can get started with running the script doing something like:

```
  . bin/impala-config.sh
  ./bin/bootstrap_toolchain.py
  ./buildall.sh -cmake_only -noclean
  make thrift-deps
  ./bin/parse-thrift-profile.py ./impala_profile_log_1.1-1594189561854
```
