### ISSUE TITLE
Support lists/tuples as context.execute() parameters

### ISSUE THREAD

**Issue by felipecruz** [cloudera/impyla#54]
PEP 249 defines that `context.execute(statement, parameters)` should support parameters as sequences or mappings. If you pass, for instance a list, it fails with `AttributeError`

**Comment by laserson** [comment]
My reading of PEP 249 makes me think that the `paramstyle` variable determines the format of the parameters that should be accepted in `.execute()`.  Since we picked `pyformat`, I figured we only need to support dictionaries.  How would it even make sense to support a list?

Also, supporting a list of tuples is deprecated in favor of `.executemany`.

Thoughts?

**Comment by felipecruz** [comment]
Ok.. I didn't seen that `pyformat` was the choice for `impyla`. I was using something like `'where id = %s'` which is `format`. But I guess there is no point in support `format`. 

What confused me is that mysql dbapi supports lists and I'm sharing code to run both mysql and impala queries.

**Comment by felipecruz** [comment]
Hello @laserson . When I run `cursor.execute('select * from table where id = %(some_id)d', {'some_id': 1000})` I get a format error because `_bind_parameters()` converts `1000` to string. If I switch the query to `%(some_id)s` I get an `AnalysisException: operands of type INT and STRING are not comparable`.  Am I missing something here?

**Comment by laserson** [comment]
I think the problem is that it's just a mess to deal with all the format conversions between Python and SQL.  The PEP 249 spec only shows examples using `%s`, and while it doesn't explicitly state that implementations should refrain from supporting the other Python formatting operators, it seems that other projects limit to `%s`.  See the ["official" MySQL DB API docs][1], for example, from which I took inspiration.

I wouldn't think of PEP 249 parameter binding as equivalent to Python string formatting operations.  Just use named variables and only use `%s` for impyla.

[1]: http://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-execute.html

**Comment by laserson** [comment]
Also, I'm guessing `id` is `INT` type?  In the case where you got an analysis exception, I am guessing you also changed the dict value from `1000` to `"1000"`, is that right?   You should actually maintain it as a Python `int`.

I know this is a mess.  The rules to follow are:
1. Any query parameter specified as `%(name)s`.
2. Any bound value should be the corresponding type.  That's because `None` is converted to `NULL`, strings get wrapped in quotes, and other literals are converted using `.__str__()`.

**Comment by felipecruz** [comment]
>Also, I'm guessing id is INT type? In the case where you got an analysis exception, I am guessing you also changed the dict value from 1000 to "1000", is that right?

I didn't but `_bind_parameters()` always convert `1000` (int) to `"1000"` so I still got the error. Check this line: https://github.com/cloudera/impyla/blob/master/impala/dbapi/interface.py#L163 If you send a `dict` with an `int` it'll become a `dict` with a `string`.

**Comment by laserson** [comment]
So are you still getting that error? If so, could you find the generated SQL for when you get the `AnalysisException`? (You can find it on the impalad debug page.)

**Comment by felipecruz** [comment]
Python exception value and sql statement from impalad query log:

```python
AnalysisException: operands of type INT and STRING are not comparable: estabelecimento_id_endereco_cidade = '6668'
```

```sql
Sql Statement: select count(distinct usuario_email) from vendas where estabelecimento_id_endereco_cidade = 6668
```

My workaround basically changes `string_parameters[name] = str(value)` to `string_parameters[name] = value` and it works. But I'n not really aware of implications this may cause.

**Comment by laserson** [comment]
Ok, and how did you call `cursor.execute()` when you get the analysis exception?

**Comment by felipecruz** [comment]
```
cursor.execute('select * from table where id = %(some_id)s', {'some_id': '1000'})
cursor.execute('select * from table where id = %(some_id)s', {'some_id': 1000})
```

Both statements will raise `AnalysisException`.

**Comment by laserson** [comment]
Are you sure the second one is failing?  Or you're executing it exactly as you entered above?  The only way that impyla should generate `'1000'` instead of `1000` in the SQL query is if you enter the `basestring` branch in `_bind_parameters`, which can only happen if you supply the function with a string value in the dictionary.

Either way, I'm surprised that your workaround changes anything because executing `"foo %s bar" % 5` should be the exact same as executing `"foo %s bar" % str(5)`.

**Comment by felipecruz** [comment]
The workaround works because the input string changes to use `%(id)d` instead of `%s` or `%(id)s`

```
def _bind_parameters(operation, parameters):
    # inspired by MySQL Python Connector (conversion.py)
    string_parameters = {}
    for (name, value) in parameters.iteritems():
        if value is None:
            string_parameters[name] = 'NULL'
        elif isinstance(value, basestring):
            string_parameters[name] = "'" + _escape(value) + "'"
        else:
            string_parameters[name] = str(value)
    return operation % string_parameters


print(_bind_parameters("select * from table where %s", {'id': 1000}))
```

prints

```
select * from table where {'id': '1000'}
```

The `_bind_parameter()` code is from master.

**Comment by laserson** [comment]
It looks like your query has `where %s` while it *should* have `where %(id)s`.

In the example you show, it's ultimately inserting the result of `str({'id': str(1000)})` into your SQL query because it doesn't know that it needs to match the dictionary key.

Here is what I get in my interpreter:

```
>>> from impala.dbapi.interface import _bind_parameters
>>> print(_bind_parameters("select * from table where %(id)s", {'id': 1000}))
select * from table where 1000
>>> 
```

**Comment by felipecruz** [comment]
Hello! I'm sorry about my last comment.. I confused you..

```
def _bind_parameters(operation, parameters):
    # inspired by MySQL Python Connector (conversion.py)
    string_parameters = {}
    for (name, value) in parameters.iteritems():
        if value is None:
            string_parameters[name] = 'NULL'
        elif isinstance(value, basestring):
            string_parameters[name] = "'" + _escape(value) + "'"
        else:
            string_parameters[name] = str(value)
    return operation % string_parameters


print(_bind_parameters("select * from table where %(id)s", {'id': 1000}))
```
output:

```
select * from table where 1000
```

But this will throw `AnalysisException` either

**Comment by laserson** [comment]
Well, the specific query you showed is actually not valid SQL, I believe.  Perhaps you can show me the results of the Python session that creates the `AnalysisException` again?  And also include a DESCRIBE query on the table?

**Comment by felipecruz** [comment]
Ok.. I finally got it. There is no need at all to use string formats with `%d` nor `%(id)d`. Sorry to bother you with that.. :(

**Comment by laserson** [comment]
Great!  I'm glad it's working... and definitely file another issue if you run into more problems, or try the impala mailing list.

**Comment by laserson** [comment]
Also note the work at #66

**Comment by jaredleable** [comment]
Does anyone know why executing Hive SQL for configuration settings doesn't work? Seems the only way to get configuration settings set is to pass them as a parameter on the cursor.execute method.
