### ISSUE TITLE
invalid query handle

### ISSUE THREAD

**Issue by heyarnold1** [cloudera/impyla#69]
I was wandering if anyone has experienced this error and knows what maybe causing it?  We seem to suffer from it periodontally. thanks

**Comment by ishaan** [comment]
It generally means that the query has been cancelled. You can go to the Impala debug webpage ( hostname:25000 ), click on the queries tab and see what happened to your query.

**Comment by heyarnold1** [comment]
Sorry for the slow response.  If I take the same queries and use the impala CLI I have no problem.  We have found that the issue also seems to come and go in phases.  We went a week with almost all medium to large queries failing with this error but recently the problem has vanished.

**Comment by laserson** [comment]
@heyarnold1 I'm going to close this for the time being.  Please reach out again if there are more problems.  It may be more useful to send a message to the impala-user list, as this may be a more general impala problem rather than a problem with the python connector.

**Comment by bhgames** [comment]
Definitely seeing same thing. Seems to happen after connection has been open for awhile.

**Comment by avant-etl** [comment]
For the record, this happens when you make a query with impala, and then dont call fetchall() on it until after impala has decided the query's resultset has been around too long and has ejected it from it's memory, hence when impyla asks with it's query handle what the result set is, it returns "invalid query handle."

**Comment by bhgames** [comment]
^ Sorry that was me, one of my roboaccounts :)

**Comment by xutao6936** [comment]
@heyarnold1  Please tell me how to solve this problem

**Comment by kvignesh1420** [comment]
Any updates on this problem? I encounter it while fetching all the columns (24 columns) of the table in one go with around 3200 rows. Seems like it can't handle `>n` number of columns?

**Comment by timarmstrong** [comment]
It means that the query has expired, either because it was cancelled by someone else (an admin) or it timed out because there was a timeout configured on the server and the client went too long between operations. avant-etl mentioned this above.

Please file an issue with more information if you have it. People routinely use impyla with much larger numbers of columns so that can't be it.
